homework-7/problem-1/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources(:users)
  resources(:hotels)
  get 'search' => 'home#nearbylocation', as: 'search'

end

homework-7/problem-1/app/models/hotel.rb
class Hotel < ActiveRecord::Base

	geocoded_by :location
	after_validation :geocode

	belongs_to(:user)
	validates(:user_id, presence: true)
	validates(:name, presence: true)
	validates(:location, presence: true)

	has_attached_file(:photo, styles: {thumbnail: '100x100>', full: '300x300>'},
										storage: :s3,
										s3_region: 'us-east-1',
										s3_credentials: {bucket: "vares-hotel-pics",
														 access_key_id: "",
										                 secret_access_key: ""})

	validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/
end

homework-7/problem-1/app/models/user.rb
class User < ActiveRecord::Base
has_many(:hotels)
validates(:name, presence: true)
validates(:headline, presence: true)
validates(:profile, presence: true)

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

homework-7/problem-1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, except: [:index, :nearbylocation]
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:headline,:profile,:name])
  end

end

homework-7/problem-1/app/controllers/home_controller.rb
class HomeController < ApplicationController
	def nearbylocation
		@hotels = Hotel.near("#{params[:query]}", 10, )
	end

end

homework-7/problem-1/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
	def index
		@hotels = Hotel.all
	end

	def new
		@hotel = Hotel.new
	end

	def create
		Hotel.create(hotel_params.merge(user:current_user))
		redirect_to_page_with_notice(hotels_path,"Your hotel has been created. #{current_user.name}!")
	end

	def show
		findhotel
	end

	def edit
		findhotel
	end

	def update
		findhotel
		@hotel.update(hotel_params)
		redirect_to_page_with_notice(root_path,"Your hotel has been updated. #{@hotel.user.name} !")

	end

	def destroy
		findhotel
		@hotel.delete
	end



# ======================================================================================


	def hotel_params
		hotel = params[:hotel]

		if current_user.admin?
			hotel.permit(:name, :location, :description, :user_id, :photo)
		else
			hotel.permit(:name, :location, :description, :photo)
		end
	end

	def redirect_to_page_with_notice(page,notice)
		redirect_to(page,notice: notice)
	end


	def findhotel
		@hotel = Hotel.find(params[:id])
	end


end

homework-7/problem-1/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		finduser
		@hotels = @user.hotels
	end

	def edit
		finduser
	end

	def update
		finduser
		if (user_signed_in? && @user == current_user) || current_user.admin?
		@user.update(params[:user].permit(:email,:name,:headline,:profile))
		end
		if @user.valid?
			redirect_to_page(user_path(@user),'The user was updated')
		end
	end



	def finduser
		@user = User.find(params[:id])
	end

	def redirect_to_page(path,notice)
		redirect_to(path,notice: notice)
	end
end

homework-7/problem-1/app/helpers/application_helper.rb
module ApplicationHelper
end

homework-7/problem-1/app/helpers/home_helper.rb
module HomeHelper
end

homework-7/problem-1/app/helpers/hotel_helper.rb
module HotelHelper
end

homework-7/problem-1/app/helpers/hotels_helper.rb
module HotelsHelper
end

homework-7/problem-1/app/helpers/users_helper.rb
module UsersHelper
end

homework-7/problem-1/app/views/home/index.html.erb
<h1> This is Homepage</h1>

homework-7/problem-1/app/views/home/nearbylocation.html.erb
<h1>Hotel Near <%=params[:query]%></h1>

<%@hotels.each do |hotel|%>
<p><%=link_to(hotel.name,hotel_path(hotel.id))%> <%=hotel.distance.round(2)%> miles away</p>
<%end%>

homework-7/problem-1/app/views/hotels/_form.html.erb
<%= form_for(@hotel,html:{multipart: true}) do |f|%>

<p><%=f.label(:name) %></p>
<p><%=f.text_field(:name)%></p>
<p><%=f.label(:description)%></p>
<p><%=f.text_area(:description)%></p>
<p><%=f.label(:location)%></p>
<p><%=f.text_field(:location)%></p>
<p><%=f.label(:photo)%></p>
<p><%=f.file_field(:photo)%></p>
<% if current_user.admin?%>
<p><%=f.label(:user)%>
<p><%=f.collection_select(:user_id, User.all,:id, :name) %></p>
<%end%>

<p><%=f.submit%></p> 

<%end%>

homework-7/problem-1/app/views/hotels/_hotel.html.erb
<p>Name: <%=link_to(hotel.name,hotel_path(hotel.id))%></p>
<p>Detail: <%=hotel.description%></p>
<p>Location: <%=hotel.location%></p>
<p>Post by: <%=link_to(hotel.user.name,hotel.user)%></p>
<%if user_signed_in?%>
	<%if current_user.admin?||current_user == hotel.user%>
	<%=link_to('Edit',edit_hotel_path(hotel))%> <%=link_to('Delete', hotel, method: :delete)%>
	<%end%>
<%end%><br>
<%= image_tag(hotel.photo.url,class: "hotel_image")%>

homework-7/problem-1/app/views/hotels/destroy.html.erb
<h1>Delete</h1>

homework-7/problem-1/app/views/hotels/edit.html.erb
<%=render 'form'%>

homework-7/problem-1/app/views/hotels/index.html.erb
<h1>List of all Hotels</h1>

<% @hotels.each do |hotel| %>
	<%=render 'hotel',hotel: hotel%>
<%end%>

homework-7/problem-1/app/views/hotels/new.html.erb
<%= render 'form'%>

homework-7/problem-1/app/views/hotels/show.html.erb
<h1>Hotel show page</h1>

<%= render 'hotel', hotel:@hotel%>

homework-7/problem-1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Problem1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to('Home', root_path)%>
<%= link_to('Users', users_path)%>
<% if user_signed_in?%>
	<%= link_to('Sign Out',destroy_user_session_path, method: :delete)%>
	<p>Signed in as : <%=link_to(current_user.name, user_path(current_user.id))%></p>
<%else%>
	<%= link_to('Sign In',new_user_session_path)%>
<%end%>
<%= link_to('View hotels',hotels_path)%>
<%= link_to('Add new hotel',new_hotel_path)%>	
<%= form_tag search_path, method: :get do%>
<p>
	<%= text_field_tag :query, params[:query]%>
	<%= submit_tag "Search Nearby"%>
</p>
<%end%>




<p><%= flash.alert %></p>
<p><%= flash.notice %></p>


<%= yield %>

</body>
</html>

homework-7/problem-1/app/views/users/_form.html.erb
<%= form_for (@user) do |f|%>

<p><%=f.label(:name) %></p>
<p><%=f.text_field(:name)%></p>
<p><%=f.label(:email)%></p>
<p><%=f.text_field(:email)%></p>
<p><%=f.label(:headline)%></p>
<p><%=f.text_field(:headline)%></p>
<p><%=f.label(:profile)%></p>
<p><%=f.text_area(:profile)%></p>
<% if current_user.admin?%>
<p><%=f.label('Admin ?')%></p>
<p><%=f.check_box(:admin)%></p>
<%end%>
<p><%=f.submit%></p>

<%end%>

homework-7/problem-1/app/views/users/_hotel.html.erb
<p>Name: <%=link_to(hotel.name,hotel_path(hotel.id))%></p>
<p>Detail: <%=hotel.description%></p>
<p>Location: <%=hotel.location%></p>
<p>Post by: <%=link_to(hotel.user.name,hotel.user)%></p>
<%if current_user.admin?||current_user == hotel.user%>
<%=link_to('Edit',edit_hotel_path(hotel))%> <%=link_to('Delete', hotel, method: :delete)%>
<%end%><br>
<%= image_tag(hotel.photo.url,class: "hotel_image")%>

homework-7/problem-1/app/views/users/_user.html.erb
<p>Name     : <%=user.name%></p>
<p>Email    : <%=user.email%></p>
<p>Headline : <%=user.headline%></p>
<p>Profile  : <%=user.profile%></p>

<% if user == current_user || current_user.admin? %>
<%=link_to('Edit',edit_user_path(user))%>
<%end%>

homework-7/problem-1/app/views/users/edit.html.erb
<h1>Edit page</h1>

<%=render('form')%>

homework-7/problem-1/app/views/users/index.html.erb
<h1>List of all users</h1>

<% @users.each do |user| %>

<h3><%=link_to(user.name,user)%></h3>
<p><%=user.headline%></p>

<%end%>

homework-7/problem-1/app/views/users/show.html.erb
<h1>Show</h1>

<%=render 'user',user:@user%>

<%@hotels.each do |hotel|%>
<%=render 'hotel',hotel:hotel%>
<%end%>

homework-7/problem-1/app/views/users/update.html.erb
<h1>Edit</h1>

<ul>
<%@user.errors.full_messages.each do |error|%>
	<li><%=error%></li>
<%end%>
</ul>



<%=render('form')%>