homework-5/problem-2/config/routes.rb
Rails.application.routes.draw do
  root ('items#index')
  resources(:items)
end

homework-5/problem-2/app/models/address.rb
class Address < ActiveRecord::Base
	has_many :user_addresses
	has_many :users, :through => :useraddresses
end

homework-5/problem-2/app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to (:user)
end

homework-5/problem-2/app/models/user.rb
class User < ActiveRecord::Base
	has_many :items
	has_many :useraddresses
	has_many :addresses, :through => :useraddresses
end

homework-5/problem-2/app/models/useraddress.rb
class Useraddress < ActiveRecord::Base
	belongs_to :user
	belongs_to :address
end

homework-5/problem-2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  Time.zone = 'Eastern Time (US & Canada)'
  protect_from_forgery with: :exception
end

homework-5/problem-2/app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
	  @Items = Item.all
	end

	def show
	  @Item = Item.find(params[:id])
	end

	def new
	  @Item = Item.new
	end

	def create
	  Item.create(params[:item].permit(:name, :quantity, :price))
	end

	def edit
	  @Item = Item.find(params[:id])
	end

	def update
	  @Item = Item.find(params[:id])
	  @Item.update(params[:item].permit(:name, :quantity, :price))
	end

	def destroy
	  @Item = Item.find(params[:id])
	  @Item.delete
	end
end

homework-5/problem-2/app/helpers/fake_ebay_helper.rb
module FakeEbayHelper
end

homework-5/problem-2/app/helpers/item_helper.rb
module ItemHelper
end

homework-5/problem-2/app/views/items/create.html.erb
<h1>Congratulation!! Your Item has been added</h1>

homework-5/problem-2/app/views/items/edit.html.erb
<h1>Edit</h1>

<%=form_for(@Item) do |f| %>
  <p><%= f.label(:name)%></p>
  <p><%= f.text_field(:name)%></p>
  <P><%= f.label(:quantity)%></P>
  <p><%= f.text_field(:quantity)%></p>
  <p><%= f.label(:price)%></p>
  <p><%= f.text_field(:price)%></p>

  <%= f.submit('Submit')%>
 
<%end%>

homework-5/problem-2/app/views/items/index.html.erb
<h1>Items</h1>
<ul>
<%@Items.each do |item| %>
<li><%=link_to(item.name, item)%></li>
<p><%=link_to('Edit', edit_item_path(item))%> <%=link_to('Delete', item_path(item), method: :delete)%></p>
<%end%>
</ul>

homework-5/problem-2/app/views/items/new.html.erb
<h1>Add New Item</h1>

<%=form_for(@Item) do |f| %>
  <p><%= f.label(:name)%></p>
  <p><%= f.text_field(:name)%></p>
  <P><%= f.label(:quantity)%></P>
  <p><%= f.text_field(:quantity)%></p>
  <p><%= f.label(:price)%></p>
  <p><%= f.text_field(:price)%></p>

  <%= f.submit('Add')%>
 
<%end%>

homework-5/problem-2/app/views/items/show.html.erb
<h1>Show Items</h1>
<h2><%=@Item.name%></h2>
<p>In stock    : <%=@Item.quantity%></p>
<p>Price       : $<%=@Item.price%></p>
<p>Last updated: <%=@Item.updated_at%></p>

homework-5/problem-2/app/views/items/update.html.erb
<h1>Update</h1>

homework-5/problem-2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Problem2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
	<%= link_to('All Items', items_path)%>
	<%= link_to('New Items', new_item_path)%>
</nav>

<%= yield %>

</body>
</html>